name_mapping = {
    "name": "Name",
    "class": "Class",
    "sunset": "Sunset",
    "address": "Address",
    "cq_zone": "CQ Zone",
    "lookups": "Lookups",
    "sunrise": "Sunrise",
    "itu_zone": "ITU Zone",
    "latitude": "Latitude",
    "qsl_info": "QSL Info",
    "longitude": "Longitude",
    "qrz_admin": "Account admin",
    "uses_lotw": "Uses LoTW",
    "qrz_record": "QRZ Record",
    "date_joined": "Date Joined",
    "grid_square": "Grid Square",
    "last_update": "Last Update",
    "qsl_by_eqsl": "QSL by eQSL",
    "qsl_by_mail": "QSL by Mail",
    "mean_frequency": "Average emmision frequency",
    "median_frequency": "Average emmision frequency",
    "start_date": "First recorded emmision",
    "end_date": "Last recorded emmision",
    "recorded_time": "Total recorded time",
    "Comment": "Comment",
    "Freq": "Frecuency of the message",
    "URL": "Found urls",
    "born": "Born in",
    "us_state": "US State",
    "us_county": "US County",
    "effective": "Effective",
    "gmt_offset": "Gmt Offset",
    "fcc_record_": "FCC Record",
    "alias": "Aliases",
}
